<?php

function arche_mde_api_page_attachments(&$page)
{
    // This could in most cases be added in template as well with:
    // {{ attach_library('acdh-repo/acdh-repo-css-and-js') }}
    //$page['#attached']['library'][] = 'acdh-repo-gui-css-and-js';
}

function arche_mde_api_theme($existing, $type, $theme, $path)
{
    return [
        'arche-gui-api-main' => [
            'variables' => ['data' => NULL]
        ]
    ];
}

// Setup custom 404!
// -> add file "page--404.html.twig" to theme template folder
function arche_mde_api_theme_suggestions_page(array $variables)
{
    $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));

    $suggestions = theme_get_suggestions($path_args, 'page');

    $http_error_suggestions = [
        'system.404' => 'page__404',
    ];

    $route_name = \Drupal::routeMatch()->getRouteName();

    if (isset($http_error_suggestions[$route_name])) {
        $suggestions[] = $http_error_suggestions[$route_name];
    }

    return $suggestions;
}

/*
 * Create a hook for the admin form page to we can use an external javascript file
 * 
 */
function arche_mde_api_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
 
    //form and user permission settings for the collection download views
    $form['#attached']['library'][] = 'arche_mde_api/mylibrary';
    $form['#attached']['drupalSettings']['arche_mde_api']['users']['id'] = \Drupal::currentUser()->id();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $form['#attached']['drupalSettings']['arche_mde_api']['users']['name'] = $account->getAccountName();
    $roles = array();
    $roles = \Drupal::currentUser()->getRoles();
    if(count($roles) > 0){ $roles = implode(",", $roles); }
    $form['#attached']['drupalSettings']['arche_mde_api']['users']['roles'] = $roles;
    
    $current_path = \Drupal::service('path.current')->getPath();
    
    return $form;
}



